name: Continuous Integration (Dev)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_IMAGE: ${{ vars.DOCKER_REGISTRY }}/chat
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_USER_FILE_SIZE_LIMIT: ${{ vars.NEXT_PUBLIC_USER_FILE_SIZE_LIMIT }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=sha,format=long,prefix=
          type=raw,value={{date 'YYYYMMDDTHHmmss' tz='Asia/Bangkok'}}-${{ github.sha }}

    - name: Build a Docker image
      uses: docker/build-push-action@v4
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        build-args: |
          NEXT_PUBLIC_SUPABASE_URL=${{ env.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_USER_FILE_SIZE_LIMIT=${{ env.NEXT_PUBLIC_USER_FILE_SIZE_LIMIT }}

    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        scanners: vuln
        exit-code: '0' # FIXME: Temporarily disinterested...
        ignore-unfixed: true
        image-ref: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        severity: 'CRITICAL,HIGH'

    - name: Login to Amazon ECR
      if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.AWS_ACCESS_KEY_ID }}
        password: ${{ env.AWS_SECRET_ACCESS_KEY }}

    - name: Push the Docker image
      if: ${{ github.event_name == 'push' }}
      uses: docker/build-push-action@v4
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ./Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          NEXT_PUBLIC_SUPABASE_URL=${{ env.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_USER_FILE_SIZE_LIMIT=${{ env.NEXT_PUBLIC_USER_FILE_SIZE_LIMIT }}
